apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-4519
spec:
  project: default
  source:
    repoURL: 'https://github.com/jopit/argocd-4519'
    path: manifests
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default

